// Generated by CoffeeScript 1.5.0-pre
(function() {
  var app, fileServer, handler, port, static_;

  handler = function(request, response) {
    request.addListener("end", function() {});
    return fileServer.serve(request, response);
  };

  app = require("http").createServer(handler);

  static_ = require("node-static");

  fileServer = new static_.Server("./public");

  port = process.env.PORT || 8080;

    console.log("using port "+port)
  app.listen(port);

}).call(this);
