// Generated by CoffeeScript 1.5.0-pre
(function() {
  var app, fileServer, handler, static_;

  handler = function(request, response) {
    request.addListener("end", function() {});
    return fileServer.serve(request, response);
  };

  app = require("http").createServer(handler);

  static_ = require("node-static");

  fileServer = new static_.Server("./public");

  app.listen(8080);

}).call(this);
